FROM apache/airflow:2.9.3-python3.10

USER root
RUN apt-get update && apt-get install -y \
    wget gnupg libglib2.0-0 libnss3 libnspr4 libatk1.0-0 \
    libdbus-1-3 libx11-6 libxcomposite1 libxdamage1 libxext6 \
    libxfixes3 libxrandr2 libgbm1 libxcb1 libxkbcommon0 \
    libasound2 libatspi2.0-0 libgtk-3-0 libcups2 libdrm2 \
    libpango-1.0-0 libpangocairo-1.0-0 \
    && apt-get clean

USER airflow
RUN pip install --no-cache-dir pandas groq playwright

USER root
RUN python -m playwright install chromium

COPY airflow_home/dags /opt/airflow/dags
COPY airflow_home/services /opt/airflow/services

COPY entry.sh /entry.sh
RUN chmod +x /entry.sh

EXPOSE 8080
ENTRYPOINT ["/bin/bash", "/entry.sh"]