# Generated by Django 6.0.5 on 2026-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_net', models.BooleanField(default=False)),
                ('is_gross', models.BooleanField(default=False)),
                ('is_full_time', models.BooleanField(default=False)),
                ('is_part_time', models.BooleanField(default=False)),
                ('hard_skills', models.ManyToManyField(blank=True, to='backend.hardskill')),
                ('locations', models.ManyToManyField(blank=True, to='backend.location')),
                ('soft_skills', models.ManyToManyField(blank=True, to='backend.softskill')),
            ],
        ),
    ]
